# Generated by Django 5.0.7 on 2024-12-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
