# Generated by Django 5.0.7 on 2024-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
