# Generated by Django 5.0.7 on 2024-12-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_1', '0002_userprofile_full_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
